:graphite: http://vejao.mireveja.vtex.com.br:8085
# :graphite: http://ec2-54-224-232-60.compute-1.amazonaws.com:8085
# :templatedir: /opt/dashboard/graph_templates
:templatedir: graph_templates
#:username: admin
#:password: secret
:options:
  :title: "VejaO MireVeja"
  :prefix: ""
  :refresh_rate: 1
  :graph_columns: 3
  :graph_width: 500
  :graph_height: 350
  :interval_filters:
    - :label: 15 minutos
      :from: -15minute
      :to: now
    - :label: 1 hora
      :from: -1hour
      :to: now
    - :label: 2 horas
      :from: -2hour	
    - :label: 6 Horas
      :from: -6hour
    - :label: 1 dia
      :from: -1day
    - :label: 1 semana
      :from: -7day
    - :label: 1 mês
      :from: -1month
  :intervals:
    - [ "-1hour", "1 hora" ]
    - [ "-2hour", "2 horas" ]
    - [ "-6hour", "6 horas" ]
    - [ "-7day", "1 semana" ]
    - [ "-15day", "15 dias" ]
    - [ "-1month", "1 mês" ]
