:graphite: http://ec2-54-224-232-60.compute-1.amazonaws.com:8085
:templatedir: /opt/gdash/graph_templates
#:username: admin
#:password: secret
:options:
  :title: MireVeja
  :prefix: ""
  :refresh_rate: 60
  :graph_columns: 2
  :graph_width: 500
  :graph_height: 250
  :interval_filters:
    - :label: Last Hour
      :from: -1hour
      :to: now
    - :label: Last Day
      :from: -1day
    - :label: Last Week
      :from: -1week
    - :label: Last Month
      :from: -1month
    - :label: Last Year
      :from: -1year
  :intervals:
    - [ "-1hour", "1 hour" ]
    - [ "-2hour", "2 hour" ]
    - [ "-1day", "1 day" ]
    - [ "-1month", "1 month" ]
    - [ "-1year", "1 year" ]
