:graphite: http://ec2-54-224-232-60.compute-1.amazonaws.com:8085
:templatedir: /opt/gdash/graph_templates
#:username: admin
#:password: secret
:options:
  :title: MireVeja
  :prefix: ""
  :refresh_rate: 1
  :graph_columns: 3
  :graph_width: 450
  :graph_height: 300
  :interval_filters:
    - :label: Última Hora
      :from: -1hora
      :to: now
    - :label: "6 Horas antes"
      :from: -6hour
    - :label: "1 dia antes"
      :from: -1day
    - :label: "1 semana antes"
      :from: -7day
    - :label: "1 mês antes"
      :from: -1month
  :intervals:
    - [ "-1hour", "1 hora" ]
    - [ "-6hour", "6 horas" ]
    - [ "-7day", "1 semana" ]
    - [ "-15day", "15 dias" ]
    - [ "-1month", "1 mes" ]
